# Generated by Django 6.1.1 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.CharField(max_length=20, unique=True)),
                ("subject_code", models.CharField(max_length=20, unique=True)),
                ("subject_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("credits", models.PositiveIntegerField(default=3)),
                ("semester", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
    ]
